homeassistant:
  name: Argonne
  latitude: !secret lat
  longitude: !secret lon
  elevation: !secret ele
  unit_system: imperial
  time_zone: America/New_York

  customize: !include customize.yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_pw
  max_retries: 3
  default_measurement: state

config:

cloud:

http:
  base_url: !secret base_url

frontend:
  javascript_version: latest

discovery:

updater:

sun:

wemo:

hue:
  bridges:
    - host: !secret hue_host

ifttt:
  key: !secret ifttt_key

history:

logbook:

tts:
  - platform: google

panel_iframe: !include_dir_merge_named panel
sensor: !include_dir_merge_named sensor
group: !include_dir_merge_named group
automation: !include_dir_merge_named automation
script: !include_dir_merge_named script